<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AR.Iec61850\AR.Iec61850.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpPcap" Version="6.3.1" />
  </ItemGroup>

  <PropertyGroup>
    <Copyright>Copyright (C) 2026 Mas Ari / masarray</Copyright>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
