using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using AR.Iec61850.Capture;
using AR.Iec61850.Diagnostics.Binding;
using AR.Iec61850.Diagnostics.Goose;
using AR.Iec61850.Diagnostics.SampledValues;
using AR.Iec61850.Monitoring;
using AR.Iec61850.Scl;
using AR.Iec61850.Scl.Engineering;

namespace AR.Iec61850.Simulation;

public sealed class EngineeringWorkbenchEvidencePackOptions
{
    public string SclPath { get; init; } = Path.Combine("samples", "scl", "minimal-station.scd");
    public string PcapPath { get; init; } = string.Empty;
    public string OutputFolder { get; init; } = Path.Combine(".artifacts", "workbench-pack");
    public double NominalFrequencyHz { get; init; } = 50;
    public bool IncludePublicAlphaReadiness { get; init; } = true;
    public int Port { get; init; }
    public int ProbeTimeoutMilliseconds { get; init; } = 5000;
    public int SimulationSteps { get; init; } = 6;
}

public sealed class EngineeringWorkbenchEvidencePack
{
    public string Version { get; init; } = "N5.39";
    public DateTimeOffset CreatedAtUtc { get; init; } = DateTimeOffset.UtcNow;
    public string SclPath { get; init; } = string.Empty;
    public string SclSourceName { get; init; } = string.Empty;
    public string PcapPath { get; init; } = string.Empty;
    public string OutputFolder { get; init; } = string.Empty;
    public bool IsComplete { get; init; }
    public bool HasPcapEvidence { get; init; }
    public bool PublicAlphaReady { get; init; }
    public int ArtifactCount => Artifacts.Count;
    public int FindingCount => Findings.Count;
    public int BlockingFindingCount => Findings.Count(f => string.Equals(f.Severity, "High", StringComparison.OrdinalIgnoreCase));
    public int WarningFindingCount => Findings.Count(f => string.Equals(f.Severity, "Warning", StringComparison.OrdinalIgnoreCase));
    public int SclIedCount { get; init; }
    public int SclLogicalDeviceCount { get; init; }
    public int SclLogicalNodeCount { get; init; }
    public int SclDataSetCount { get; init; }
    public int SclReportControlCount { get; init; }
    public int ExpectedGooseCount { get; init; }
    public int BoundGooseCount { get; init; }
    public int ExpectedSampledValuesCount { get; init; }
    public int BoundSampledValuesCount { get; init; }
    public int ObservedPacketCount { get; init; }
    public int ObservedDecodedFrameCount { get; init; }
    public int ObservedOtherFrameCount { get; init; }
    public bool ProcessBusBindingReady { get; init; }
    public bool GooseDiagnosticsHealthy { get; init; }
    public bool SampledValuesDiagnosticsHealthy { get; init; }
    public bool ReadOnlyMmsLoopbackReady { get; init; }
    public IReadOnlyList<EngineeringWorkbenchEvidenceArtifact> Artifacts { get; init; } = Array.Empty<EngineeringWorkbenchEvidenceArtifact>();
    public IReadOnlyList<EngineeringWorkbenchEvidenceFinding> Findings { get; init; } = Array.Empty<EngineeringWorkbenchEvidenceFinding>();

    public string Summary => $"workbench evidence pack: complete={IsComplete.ToString().ToLowerInvariant()} artifacts={ArtifactCount} blocking={BlockingFindingCount} warnings={WarningFindingCount} SCL={SclSourceName} packets={ObservedPacketCount} binding={(ProcessBusBindingReady ? "ready" : "check")} GOOSE={BoundGooseCount}/{ExpectedGooseCount} SV={BoundSampledValuesCount}/{ExpectedSampledValuesCount} MMS={(ReadOnlyMmsLoopbackReady ? "ready" : "check")}";

    public string ToMarkdown()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Engineering Workbench Evidence Pack");
        sb.AppendLine();
        sb.AppendLine("This evidence pack is generated by the read-only engineering workbench harness. It groups SCL engineering, process-bus binding, GOOSE diagnostics, Sampled Values diagnostics, MMS read-only loopback readiness, and optional public-alpha readiness into a repeatable review folder.");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Value |");
        sb.AppendLine("| --- | ---: |");
        sb.AppendLine($"| Version | {Escape(Version)} |");
        sb.AppendLine($"| Complete | {IsComplete.ToString().ToLowerInvariant()} |");
        sb.AppendLine($"| SCL source | {Escape(SclSourceName)} |");
        sb.AppendLine($"| PCAP evidence | {(HasPcapEvidence ? Escape(Path.GetFileName(PcapPath)) : "not provided")} |");
        sb.AppendLine($"| Artifacts | {ArtifactCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Blocking findings | {BlockingFindingCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Warning findings | {WarningFindingCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| IEDs | {SclIedCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Logical devices | {SclLogicalDeviceCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Logical nodes | {SclLogicalNodeCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| DataSets | {SclDataSetCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Reports | {SclReportControlCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| GOOSE bound | {BoundGooseCount.ToString(CultureInfo.InvariantCulture)}/{ExpectedGooseCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| SV bound | {BoundSampledValuesCount.ToString(CultureInfo.InvariantCulture)}/{ExpectedSampledValuesCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Observed packets | {ObservedPacketCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Decoded process-bus frames | {ObservedDecodedFrameCount.ToString(CultureInfo.InvariantCulture)} |");
        sb.AppendLine($"| Process-bus binding | {(ProcessBusBindingReady ? "ready" : "check")} |");
        sb.AppendLine($"| GOOSE diagnostics | {(GooseDiagnosticsHealthy ? "healthy" : "check")} |");
        sb.AppendLine($"| SV diagnostics | {(SampledValuesDiagnosticsHealthy ? "healthy" : "check")} |");
        sb.AppendLine($"| MMS read-only loopback | {(ReadOnlyMmsLoopbackReady ? "ready" : "check")} |");
        sb.AppendLine($"| Public alpha gate | {(PublicAlphaReady ? "ready" : "not included / check")} |");
        sb.AppendLine();

        sb.AppendLine("## Artifact Index");
        sb.AppendLine();
        sb.AppendLine("| Artifact | Kind | Bytes | SHA-256 | Description |");
        sb.AppendLine("| --- | --- | ---: | --- | --- |");
        foreach (var artifact in Artifacts)
            sb.AppendLine($"| `{Escape(artifact.RelativePath)}` | {Escape(artifact.Kind)} | {artifact.SizeBytes.ToString(CultureInfo.InvariantCulture)} | `{Escape(artifact.Sha256)}` | {Escape(artifact.Description)} |");
        if (Artifacts.Count == 0)
            sb.AppendLine("| - | - | - | - | - |");
        sb.AppendLine();

        sb.AppendLine("## Findings");
        sb.AppendLine();
        sb.AppendLine("| Severity | Area | Code | Message | Recommendation |");
        sb.AppendLine("| --- | --- | --- | --- | --- |");
        foreach (var finding in Findings)
            sb.AppendLine($"| {Escape(finding.Severity)} | {Escape(finding.Area)} | `{Escape(finding.Code)}` | {Escape(finding.Message)} | {Escape(finding.Recommendation)} |");
        if (Findings.Count == 0)
            sb.AppendLine("| Info | workbench | `EVIDENCE_PACK_OK` | Evidence pack generated without blocking finding. | Keep build, test, CI, and source-clean gates green before public tagging. |");
        sb.AppendLine();

        sb.AppendLine("## Scope Boundary");
        sb.AppendLine();
        sb.AppendLine("- This pack is a developer-preview engineering evidence artifact, not a conformance certificate.");
        sb.AppendLine("- Workbench runs are read-only by default; write operations remain guarded in MMS loopback profiles.");
        sb.AppendLine("- Missing GOOSE/SV observations are expected when no PCAP/live capture is provided.");
        sb.AppendLine("- Product applications should consume this evidence schema rather than duplicating profile logic.");
        return sb.ToString();
    }

    public string ToJson(JsonSerializerOptions? options = null)
        => JsonSerializer.Serialize(this, options ?? new JsonSerializerOptions { WriteIndented = true });

    private static string Escape(string? value)
        => (value ?? string.Empty).Replace("|", "\\|", StringComparison.Ordinal).ReplaceLineEndings(" ");
}

public sealed record EngineeringWorkbenchEvidenceArtifact
{
    public string RelativePath { get; init; } = string.Empty;
    public string Kind { get; init; } = string.Empty;
    public long SizeBytes { get; init; }
    public string Sha256 { get; init; } = string.Empty;
    public string Description { get; init; } = string.Empty;
}

public sealed record EngineeringWorkbenchEvidenceFinding
{
    public string Severity { get; init; } = "Info";
    public string Area { get; init; } = string.Empty;
    public string Code { get; init; } = string.Empty;
    public string Message { get; init; } = string.Empty;
    public string Recommendation { get; init; } = string.Empty;
}

public sealed class EngineeringWorkbenchEvidencePackBuilder
{
    public async Task<EngineeringWorkbenchEvidencePack> RunAsync(
        EngineeringWorkbenchEvidencePackOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        options ??= new EngineeringWorkbenchEvidencePackOptions();
        if (string.IsNullOrWhiteSpace(options.SclPath))
            throw new ArgumentException("SCL path is required.", nameof(options));
        if (!File.Exists(options.SclPath))
            throw new FileNotFoundException("SCL file was not found.", options.SclPath);

        var outputFolder = string.IsNullOrWhiteSpace(options.OutputFolder)
            ? Path.Combine(".artifacts", "workbench-pack")
            : options.OutputFolder;
        Directory.CreateDirectory(outputFolder);

        var jsonOptions = new JsonSerializerOptions { WriteIndented = true };
        var artifacts = new List<EngineeringWorkbenchEvidenceArtifact>();
        var findings = new List<EngineeringWorkbenchEvidenceFinding>();

        var scl = new SclEngineeringProfileBuilder().Load(options.SclPath);
        foreach (var finding in scl.Findings)
            findings.Add(new EngineeringWorkbenchEvidenceFinding { Severity = finding.Severity, Area = "SCL", Code = finding.Code, Message = finding.Message, Recommendation = "Review the SCL engineering profile artifact." });

        var observation = Observe(options.SclPath, options.PcapPath, options.NominalFrequencyHz);
        var sourceName = Path.GetFileName(options.SclPath);
        var binding = new ExpectedObservedBindingProfileBuilder().Build(scl, observation.Summaries, sourceName);
        var goose = new GooseDiagnosticsProfileBuilder().Build(scl, observation.Summaries, sourceName);
        var sv = new SampledValuesDiagnosticsProfileBuilder().Build(scl, observation.Summaries, sourceName);
        var mms = await new MmsReadOnlyServerLoopbackProfileBuilder().RunAsync(
            new MmsReadOnlyServerLoopbackOptions
            {
                Port = options.Port,
                ProbeTimeoutMilliseconds = options.ProbeTimeoutMilliseconds,
                SimulationSteps = options.SimulationSteps
            },
            cancellationToken).ConfigureAwait(false);

        PublicAlphaReadinessProfile? publicAlpha = null;
        if (options.IncludePublicAlphaReadiness)
        {
            publicAlpha = await new PublicAlphaReadinessProfileBuilder().RunAsync(
                new PublicAlphaReadinessOptions
                {
                    SclPath = options.SclPath,
                    Port = options.Port,
                    ProbeTimeoutMilliseconds = options.ProbeTimeoutMilliseconds,
                    SimulationSteps = options.SimulationSteps
                },
                cancellationToken).ConfigureAwait(false);
        }

        AddFindings(findings, binding.Findings.Select(f => new EngineeringWorkbenchEvidenceFinding { Severity = f.Severity, Area = "binding", Code = f.Code, Message = f.Message, Recommendation = "Compare expected SCL process-bus streams against the observed capture." }));
        AddFindings(findings, goose.Findings.Select(f => new EngineeringWorkbenchEvidenceFinding { Severity = f.Severity, Area = "GOOSE", Code = f.Code, Message = f.Message, Recommendation = f.Recommendation }));
        AddFindings(findings, sv.Findings.Select(f => new EngineeringWorkbenchEvidenceFinding { Severity = f.Severity, Area = "SV", Code = f.Code, Message = f.Message, Recommendation = f.Recommendation }));
        AddFindings(findings, mms.Findings.Select(f => new EngineeringWorkbenchEvidenceFinding { Severity = "Warning", Area = "MMS", Code = "MMS_LOOPBACK_FINDING", Message = f, Recommendation = "Review the MMS read-only loopback profile artifact." }));
        if (publicAlpha is not null)
            AddFindings(findings, publicAlpha.Findings.Select(f => new EngineeringWorkbenchEvidenceFinding { Severity = f.Severity, Area = f.Area, Code = f.Code, Message = f.Message, Recommendation = f.Recommendation }));

        artifacts.Add(WriteArtifact(outputFolder, "profiles/scl-engineering-profile.md", "markdown", scl.ToMarkdown(), "SCL engineering profile."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/scl-engineering-profile.json", "json", JsonSerializer.Serialize(scl, jsonOptions), "SCL engineering profile JSON."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/process-bus-binding-profile.md", "markdown", binding.ToMarkdown(), "Expected-vs-observed process-bus binding profile."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/process-bus-binding-profile.json", "json", JsonSerializer.Serialize(binding, jsonOptions), "Expected-vs-observed process-bus binding JSON."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/goose-diagnostics-profile.md", "markdown", goose.ToMarkdown(), "GOOSE diagnostics profile."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/goose-diagnostics-profile.json", "json", JsonSerializer.Serialize(goose, jsonOptions), "GOOSE diagnostics JSON."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/sv-diagnostics-profile.md", "markdown", sv.ToMarkdown(), "Sampled Values diagnostics profile."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/sv-diagnostics-profile.json", "json", JsonSerializer.Serialize(sv, jsonOptions), "Sampled Values diagnostics JSON."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/mms-readonly-loopback-profile.md", "markdown", mms.ToMarkdown(), "MMS read-only loopback profile."));
        artifacts.Add(WriteArtifact(outputFolder, "profiles/mms-readonly-loopback-profile.json", "json", mms.ToJson(jsonOptions), "MMS read-only loopback JSON."));
        if (publicAlpha is not null)
        {
            artifacts.Add(WriteArtifact(outputFolder, "profiles/public-alpha-readiness-profile.md", "markdown", publicAlpha.ToMarkdown(), "Public alpha readiness profile."));
            artifacts.Add(WriteArtifact(outputFolder, "profiles/public-alpha-readiness-profile.json", "json", publicAlpha.ToJson(jsonOptions), "Public alpha readiness JSON."));
        }

        var distinctFindings = findings
            .GroupBy(f => $"{f.Severity}|{f.Area}|{f.Code}|{f.Message}", StringComparer.OrdinalIgnoreCase)
            .Select(g => g.First())
            .OrderByDescending(f => SeverityRank(f.Severity))
            .ThenBy(f => f.Area, StringComparer.OrdinalIgnoreCase)
            .ThenBy(f => f.Code, StringComparer.OrdinalIgnoreCase)
            .ToArray();

        var pack = new EngineeringWorkbenchEvidencePack
        {
            SclPath = Path.GetFullPath(options.SclPath),
            SclSourceName = sourceName,
            PcapPath = string.IsNullOrWhiteSpace(options.PcapPath) ? string.Empty : Path.GetFullPath(options.PcapPath),
            OutputFolder = Path.GetFullPath(outputFolder),
            HasPcapEvidence = File.Exists(options.PcapPath),
            PublicAlphaReady = publicAlpha?.IsReady ?? false,
            SclIedCount = scl.Ieds.Count,
            SclLogicalDeviceCount = scl.LogicalDevices.Count,
            SclLogicalNodeCount = scl.LogicalNodes.Count,
            SclDataSetCount = scl.DataSetCount,
            SclReportControlCount = scl.ReportControlCount,
            ExpectedGooseCount = binding.ExpectedGooseCount,
            BoundGooseCount = binding.BoundGooseCount,
            ExpectedSampledValuesCount = binding.ExpectedSampledValuesCount,
            BoundSampledValuesCount = binding.BoundSampledValuesCount,
            ObservedPacketCount = observation.PacketCount,
            ObservedDecodedFrameCount = observation.DecodedFrameCount,
            ObservedOtherFrameCount = observation.OtherFrameCount,
            ProcessBusBindingReady = binding.IsReady,
            GooseDiagnosticsHealthy = goose.IsHealthy,
            SampledValuesDiagnosticsHealthy = sv.IsHealthy,
            ReadOnlyMmsLoopbackReady = mms.IsReady,
            IsComplete = scl.Ieds.Count > 0 && mms.IsReady && artifacts.Count >= 10,
            Artifacts = artifacts,
            Findings = distinctFindings
        };

        artifacts.Add(WriteArtifact(outputFolder, "README.md", "markdown", pack.ToMarkdown(), "Evidence pack review summary and artifact index."));
        var finalPack = new EngineeringWorkbenchEvidencePack
        {
            SclPath = pack.SclPath,
            SclSourceName = pack.SclSourceName,
            PcapPath = pack.PcapPath,
            OutputFolder = pack.OutputFolder,
            IsComplete = pack.IsComplete,
            HasPcapEvidence = pack.HasPcapEvidence,
            PublicAlphaReady = pack.PublicAlphaReady,
            SclIedCount = pack.SclIedCount,
            SclLogicalDeviceCount = pack.SclLogicalDeviceCount,
            SclLogicalNodeCount = pack.SclLogicalNodeCount,
            SclDataSetCount = pack.SclDataSetCount,
            SclReportControlCount = pack.SclReportControlCount,
            ExpectedGooseCount = pack.ExpectedGooseCount,
            BoundGooseCount = pack.BoundGooseCount,
            ExpectedSampledValuesCount = pack.ExpectedSampledValuesCount,
            BoundSampledValuesCount = pack.BoundSampledValuesCount,
            ObservedPacketCount = pack.ObservedPacketCount,
            ObservedDecodedFrameCount = pack.ObservedDecodedFrameCount,
            ObservedOtherFrameCount = pack.ObservedOtherFrameCount,
            ProcessBusBindingReady = pack.ProcessBusBindingReady,
            GooseDiagnosticsHealthy = pack.GooseDiagnosticsHealthy,
            SampledValuesDiagnosticsHealthy = pack.SampledValuesDiagnosticsHealthy,
            ReadOnlyMmsLoopbackReady = pack.ReadOnlyMmsLoopbackReady,
            Artifacts = artifacts,
            Findings = pack.Findings
        };
        artifacts.Add(WriteArtifact(outputFolder, "manifest.json", "json", finalPack.ToJson(jsonOptions), "Machine-readable evidence pack manifest."));

        return new EngineeringWorkbenchEvidencePack
        {
            SclPath = finalPack.SclPath,
            SclSourceName = finalPack.SclSourceName,
            PcapPath = finalPack.PcapPath,
            OutputFolder = finalPack.OutputFolder,
            IsComplete = finalPack.IsComplete,
            HasPcapEvidence = finalPack.HasPcapEvidence,
            PublicAlphaReady = finalPack.PublicAlphaReady,
            SclIedCount = finalPack.SclIedCount,
            SclLogicalDeviceCount = finalPack.SclLogicalDeviceCount,
            SclLogicalNodeCount = finalPack.SclLogicalNodeCount,
            SclDataSetCount = finalPack.SclDataSetCount,
            SclReportControlCount = finalPack.SclReportControlCount,
            ExpectedGooseCount = finalPack.ExpectedGooseCount,
            BoundGooseCount = finalPack.BoundGooseCount,
            ExpectedSampledValuesCount = finalPack.ExpectedSampledValuesCount,
            BoundSampledValuesCount = finalPack.BoundSampledValuesCount,
            ObservedPacketCount = finalPack.ObservedPacketCount,
            ObservedDecodedFrameCount = finalPack.ObservedDecodedFrameCount,
            ObservedOtherFrameCount = finalPack.ObservedOtherFrameCount,
            ProcessBusBindingReady = finalPack.ProcessBusBindingReady,
            GooseDiagnosticsHealthy = finalPack.GooseDiagnosticsHealthy,
            SampledValuesDiagnosticsHealthy = finalPack.SampledValuesDiagnosticsHealthy,
            ReadOnlyMmsLoopbackReady = finalPack.ReadOnlyMmsLoopbackReady,
            Artifacts = artifacts,
            Findings = finalPack.Findings
        };
    }

    private static PcapObservation Observe(string sclPath, string pcapPath, double nominalFrequencyHz)
    {
        if (string.IsNullOrWhiteSpace(pcapPath) || !File.Exists(pcapPath))
            return new PcapObservation(Array.Empty<ProcessBusStreamSummary>(), 0, 0, 0);

        var document = new SclParser().Load(sclPath);
        var monitor = new ProcessBusStreamMonitor(document, nominalFrequencyHz <= 0 ? 50 : nominalFrequencyHz);
        var packets = PcapReader.ReadAll(pcapPath);
        var decoded = 0;
        var other = 0;
        foreach (var packet in packets)
        {
            var streamEvent = monitor.Observe(packet);
            if (streamEvent.Kind == ProcessBusEventKind.Unknown)
                other++;
            else
                decoded++;
        }

        return new PcapObservation(monitor.Summaries.ToArray(), packets.Count, decoded, other);
    }

    private static EngineeringWorkbenchEvidenceArtifact WriteArtifact(string root, string relativePath, string kind, string content, string description)
    {
        var fullPath = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
        File.WriteAllText(fullPath, content, Encoding.UTF8);
        var bytes = new FileInfo(fullPath).Length;
        var sha = ComputeSha256(fullPath);
        return new EngineeringWorkbenchEvidenceArtifact
        {
            RelativePath = relativePath,
            Kind = kind,
            SizeBytes = bytes,
            Sha256 = sha,
            Description = description
        };
    }

    private static string ComputeSha256(string path)
    {
        using var stream = File.OpenRead(path);
        var hash = SHA256.HashData(stream);
        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    private static void AddFindings(ICollection<EngineeringWorkbenchEvidenceFinding> target, IEnumerable<EngineeringWorkbenchEvidenceFinding> findings)
    {
        foreach (var finding in findings)
            target.Add(finding);
    }

    private static int SeverityRank(string severity)
        => severity.Equals("High", StringComparison.OrdinalIgnoreCase) ? 3
            : severity.Equals("Warning", StringComparison.OrdinalIgnoreCase) ? 2
            : severity.Equals("Info", StringComparison.OrdinalIgnoreCase) ? 1
            : 0;

    private sealed record PcapObservation(ProcessBusStreamSummary[] Summaries, int PacketCount, int DecodedFrameCount, int OtherFrameCount);
}
